image: docker:latest
services:
  - docker:dind

stages:
  - build
  - release

build:
  stage: build
  script:
    - apk add make
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" DCGM="${DCGM_VERSION}" build
    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" push
    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" push-short
    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" push-latest

release:
  stage: release
  only:
    - tags
  script:
    - apk add make
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make REGISTRY="nvidia" DCGM="${DCGM_VERSION}" build
    - make REGISTRY="nvidia" push
    - make REGISTRY="nvidia" push-short
    - make REGISTRY="nvidia" push-latest
