image: docker:latest
services:
  - docker:dind

stages:
  - build
  - release

build:
  stage: build
  script:
    - apk add make
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHORT_SHA}" all
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHORT_SHA}" push
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHORT_SHA}" push-short
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHORT_SHA}" push-latest

release:
  stage: release
  only:
    - tags
  script:
    - apk add make
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make VERSION="${CI_COMMIT_TAG}" all
    - make VERSION="${CI_COMMIT_TAG}" push
    - make VERSION="${CI_COMMIT_TAG}" push-short
    - make VERSION="${CI_COMMIT_TAG}" push-latest
