apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-metrics-exporter
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: "2.0.0-rc.0"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/version: "2.0.0-rc.0"
      name: dcgm-exporter
    spec:
      containers:
      - image: nvidia/dcgm-exporter:2.0.0-rc.0
        env:
          - name: DCGM_EXPORTER_PORT
            value: 9400
        name: dcgm-exporter
        ports:
        - name: gpu-metrics
          containerPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
      volumes:
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
